// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQYv6YiK4940eQ4gvMy153o7Ljr1Ho_c',
    appId: '1:216426942561:web:c2476d82242288fb8f5a20',
    messagingSenderId: '216426942561',
    projectId: 'complaintsapp-f5030',
    authDomain: 'complaintsapp-f5030.firebaseapp.com',
    storageBucket: 'complaintsapp-f5030.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaumsK264NKozD5Y87MeVDjbfQUTECP3o',
    appId: '1:216426942561:android:434ab35214667f618f5a20',
    messagingSenderId: '216426942561',
    projectId: 'complaintsapp-f5030',
    storageBucket: 'complaintsapp-f5030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXoYG9KLErAh2KmXuQam3xXSj_Iumy-44',
    appId: '1:216426942561:ios:84405ec7d7952e588f5a20',
    messagingSenderId: '216426942561',
    projectId: 'complaintsapp-f5030',
    storageBucket: 'complaintsapp-f5030.firebasestorage.app',
    iosBundleId: 'com.shivamGroupProj.complaints',
  );
}
